### PR TITLE
Prep for idr

### PR DESCRIPTION
**Pull request by jburel**
Review the instructions
~~Changes to personal build needs to be removed.~~
 see https://github.com/ome/omero-ms-image-region/pull/4

### CODE REVIEW

**Comment by khaledk2** [comment]
I think it failed  because of the new build of the microservice, the service was unable to run with the following error :

`" java.lang.UnsupportedClassVersionError: com/glencoesoftware/omero/ms/image/region/OmeroVertxLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

**Comment by jburel** [comment]
The build is Java 11, Java 8 is used. We should align to Java 11 since the microservice is by default only tested using Java 11+

**Comment by khaledk2** [comment]
Yes, it is necessary to install Java 11 for molecule testing.  In addition, there is an error on sha256 for the build. 
I have created a branch based on this PR (https://github.com/khaledk2/ansible-role-omero-ms-image-region/tree/fix) and applied that and it has passed on:
https://github.com/khaledk2/ansible-role-omero-ms-image-region/actions/runs/9964537072

**Comment by jburel** [comment]
sha256 I forgot to update it after tagging see https://github.com/ome/omero-ms-image-region/releases/download/2024.07.16/SHASUMS
Since your build used Java 8, we now need to check the version on idr-testing

**Comment by khaledk2** [comment]
I have modified my local branch https://github.com/khaledk2/ansible-role-omero-ms-image-region/tree/fix  and added all the supported Java versions. 
I have used the new build on:
https://github.com/jburel/omero-ms-image-region/releases/tag/2024.07.17 from https://github.com/ome/omero-ms-image-region/pull/5
I have added a new attribute java_version whose default value is 11. 
test  has passed on:
https://github.com/khaledk2/ansible-role-omero-ms-image-region/actions/runs/9996241247

**Comment by khaledk2** [comment]
[A new microservice build](https://github.com/ome/omero-ms-image-region/releases/tag/2024.08.13) is available so I have created a new branch ([new_ms_release](https://github.com/khaledk2/ansible-role-omero-ms-image-region/tree/new_ms_release)) based on this branch. It also contains a fix for re-install issues using a new MS build.

**Pull request closed without merging**
